### ISSUE TITLE
Plans integration

### ISSUE THREAD

**Issue by carlosrenatohr** [honchkrow1995/posthurry-app#3]
One user plan, 50 contests per month, $9 per month subscription, connected to Paypal.

I want 1 plan still with 50 posts per month. 

But the pricing will be, 7 days free or 5 posts, then they have a choice to sign up for the plan or stop using it. 

A subscription of $9.99 per month or $79.99 per year

But if they sign up in the first 14 days after the 7 day free period, they can get it for $49.99 per year.

**Comment by carlosrenatohr** [comment]
New prices...The monthly price is $19 per month and the yearly price is $189 per year.

**Comment by yogasukma** [comment]
last update: trial just for 3 days
